import React, { useState } from 'react';
import { Container, Row, Col, Card, Spinner, Alert, Form, Button, Badge } from 'react-bootstrap';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import axios from 'axios';

import ChartComponent from './components/ChartComponent';
import StatsCard from './components/StatsCard';

const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000';

function AnalystInsights({ insights }) {
  if (!insights) return null;
  const { narrative, model } = insights;
  const reliable = model?.diagnostics?.reliable;

  return (
    <Card className="shadow mt-4">
      <Card.Body>
        <Card.Title className="d-flex justify-content-between align-items-center">
          <span>🤖 Analyst Note</span>
          {reliable === false && <Badge bg="warning" text="dark">Model diagnostics flagged this run</Badge>}
        </Card.Title>
        <Card.Text>{narrative?.text}</Card.Text>
        {narrative?.source && (
          <Card.Subtitle className="text-muted" style={{ fontSize: '0.8rem' }}>
            Generated by {narrative.source === 'claude' ? `Claude (${narrative.model})` : 'deterministic template (no LLM configured)'}
          </Card.Subtitle>
        )}
      </Card.Body>
    </Card>
  );
}

function App() {
  const [data, setData] = useState([]);
  const [changePoint, setChangePoint] = useState(null);
  const [stats, setStats] = useState({});
  const [events, setEvents] = useState([]);
  const [insights, setInsights] = useState(null);
  const [start, setStart] = useState(null);
  const [end, setEnd] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const fetchData = async () => {
    setLoading(true);
    setError('');
    try {
      const params = {};
      if (start) params.start = start.toISOString();
      if (end) params.end = end.toISOString();

      const [pricesRes, changePointRes, eventsRes, statsRes, insightsRes] = await Promise.allSettled([
        axios.get(`${API_BASE_URL}/api/prices`, { params }),
        axios.get(`${API_BASE_URL}/api/change-point`, { params }),
        axios.get(`${API_BASE_URL}/api/events`, { params }),
        axios.get(`${API_BASE_URL}/api/stats`, { params }),
        axios.get(`${API_BASE_URL}/api/insights`),
      ]);

      if (pricesRes.status === 'rejected') throw pricesRes.reason;

      setData(pricesRes.value.data.data ?? []);
      setChangePoint(changePointRes.status === 'fulfilled' ? changePointRes.value.data.data : null);
      setEvents(eventsRes.status === 'fulfilled' ? eventsRes.value.data.data : []);
      setStats(statsRes.status === 'fulfilled' ? statsRes.value.data.data : {});
      setInsights(insightsRes.status === 'fulfilled' ? insightsRes.value.data.data : null);
    } catch (err) {
      const message = err.response?.data?.message || err.message || 'Failed to fetch data. Please try again.';
      setError(`❌ ${message}`);
      console.error('Fetch error:', err.response?.status, err.response?.data);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container style={{ paddingTop: '2rem', paddingBottom: '2rem' }}>
      <div className="text-center mb-4">
        <h1>📈 Brent Oil Price Dashboard</h1>
        <p className="text-muted">Visualizing oil market behavior around global events</p>
      </div>

      <Row className="mb-4 justify-content-center">
        <Col xs="auto">
          <Form.Label>Start Date</Form.Label>
          <DatePicker
            selected={start}
            onChange={setStart}
            isClearable
            className="form-control"
            placeholderText="Select start"
            maxDate={end || new Date()}
          />
        </Col>
        <Col xs="auto">
          <Form.Label>End Date</Form.Label>
          <DatePicker
            selected={end}
            onChange={setEnd}
            isClearable
            className="form-control"
            placeholderText="Select end"
            minDate={start}
            maxDate={new Date()}
          />
        </Col>
        <Col xs="auto" className="d-flex align-items-end">
          <Button variant="primary" onClick={fetchData} disabled={loading}>
            {loading ? 'Applying...' : 'Apply Filters'}
          </Button>
        </Col>
      </Row>

      {loading && (
        <div className="text-center my-4">
          <Spinner animation="border" variant="primary" />
          <div>Loading data...</div>
        </div>
      )}

      {error && <Alert variant="danger">{error}</Alert>}

      {!loading && !error && (
        <>
          <Row className="mb-4">
            <Col md={6}>
              <StatsCard title="📉 Volatility" value={stats.volatility?.toFixed(4)} />
            </Col>
            <Col md={6}>
              <StatsCard title="📊 Avg Price Change" value={stats.average_change?.toFixed(4)} />
            </Col>
          </Row>

          <Card className="shadow">
            <Card.Body>
              <ChartComponent data={data} changePoint={changePoint} events={events} />
            </Card.Body>
          </Card>

          <AnalystInsights insights={insights} />
        </>
      )}
    </Container>
  );
}

export default App;
